spring.application.name=ProductCatalogService

# 1. DataSource Configuration (Network connection to MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/productService?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=R@hul!O0587

# 2. Hibernate Configuration (The Engine)
# 'update' tells Hibernate to automatically generate DDL and modify the database schema to match your Java classes.
spring.jpa.hibernate.ddl-auto=update

# 3. Verification & Logging (The Safety Net)
# Prints generated SQL to the IntelliJ console and formats it for readability.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
